version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: ./dockerbuilds/apache/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www/html/:/var/www/html
      - ./dockerbuilds/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .env
    networks:
      - backend