version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./dockerbuilds/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: always
    container_name: php
    volumes:
      - ./www/html:/var/www/html
      - ./dockerbuilds/php/php.ini:/usr/local/etc/php/php.ini:ro
    env_file:
      - .env
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www/html:/var/www/html
      - ./dockerbuilds/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    env_file:
      - .env
    networks:
      - backend